#ifndef INTERRUPTS_H
#define INTERRUPTS_H

/* ARM INTERRUPT BASE REGISTER */ 
#define ARM_INTERRUPT_BASE(offset) (*(volatile unsigned int *)(0x3E00B000 + offset))

/* ARM INTERRUPT SELECT REG */

/* ARM INTERRUPT ENABLE REG 1 */
#define ARM_INTERRUPT_ENABLE_REG1 0x210
#define AUX_INTERRUPT_ENABLE_REG1 (1 << 29) 

/* ARM INTERRUPT DISABLE REG 1 */
#define ARM_INTERRUPT_DISABLE_REG1 0x21C
#define AUX_INTERRUPT_DISABLE_REG1



#endif

void interrupt_enable();
